### PR TITLE
Test/fix broken r checks

### PR DESCRIPTION
**Pull request by AlexAxthelm**
Fixing a bunch of red bubbles that popped up now that we've made `RMI-PACTA/actions`'s R suite more robust. 

biggest changes here are in the testing suite, which maintains the original logic, but has had a major refactor in invocation. One notable addition there is the `expect_multiple_conditions()` (in a helper file), which allows for checking multiple `warning`, `error`, or `message`s pretty smoothly

### CODE REVIEW

**Review by cjyetman — DISMISSED** [review]

**Comment by AlexAxthelm** [comment]
@cjyetman any idea why the tests for column types are failing on `R < 4.0`?

**Comment by cjyetman** [comment]
> @cjyetman any idea why the tests for column types are failing on `R < 4.0`?

I have no idea what is even being tested here, but.... if I had to take a wild guess on why stuff like this is popping up

``` r
file_contents[["currency"]] has type 'integer', not 'character'.
```

I'd guess that maybe some data.frames are being created with `stringsAsFactors = TRUE` because the default changed to `stringsAsFactors = FALSE` in R v4.0?!?

**Comment by AlexAxthelm** [comment]
Thanks @cjyetman that cleared it up perfectly!

**Review by jdhoffa — APPROVED** [review]
This is a mammoth PR, but assuming it is predominantly syntactical changes to get the R R CMD check to function, I suppose LGTM

**Pull request merged**
