### PR TITLE
Feat/13 add json schema

### LINKED ISSUE #13: validate metadata output format
define a json schema for output format to ensure consistency

### LINKED ISSUE #14: Export metadata to JSON file
In `process_directory()`, need to add functionality to export metadata about exported portfolios to JSON file for integration with RMI-PACTA/app

### PR DESCRIPTION
**Pull request by AlexAxthelm**
Adds a JSON schema, validation logic to processing files, and metadata export

Closes #13 
Closes #14

### CODE REVIEW

**Comment by AlexAxthelm** [comment]
Note that as of acf0d8e070f4d2e0a239d4b718fd7b09a199b818, this is installing the GitHub version of `jsonvalidate`, which is required for the new api's `json_schema`, but is not available yet on CRAN.

**Review by cjyetman — APPROVED** [review]
honestly, I'm totally lost with all this stuff, so just rubber stamping

**Comment by AlexAxthelm** [comment]
Merging to unblock development, but opening an issue to improve documentation so that we're all comfortable with what's happening here

**Comment by jdhoffa** [comment]
Merged before I could comment, but some potential typos

**Pull request merged**
